# Generated by Django 3.2.16 on 2022-11-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0002_rename_profiles_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
