# Generated by Django 3.2.16 on 2022-11-28 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0003_auto_20221125_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='comment',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
