# Generated by Django 3.2.16 on 2022-11-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Connector', '0004_auto_20221128_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, ''), (1, 'Reserved for Collection')], default=0)),
                ('collection_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_pet', to='Connector.profile')),
                ('rescue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rescue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
